name: clean_news_ai
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 0.1.2
  worker_manager: ^2.8.9
  osam_flutter: ^3.2.9
  osam_http_client: ^0.0.3
  flutter_sticky_header: ^0.4.2
  animations: ^1.1.1
  http: ^0.12.1
  intl: ^0.16.1
  share: ^0.6.4+3

dev_dependencies:
  build_runner: ^1.10.0
  pedantic: ^1.9.0
  hive_generator:
    git:
      url: 'https://github.com/Renesanse/hive.git'
      path: hive_generator

flutter:
  uses-material-design: true
